import "./globals.css";
import {Inter, Sora} from "next/font/google";
import Navbar from "@/components/Navbar";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter", // definiujemy zmienną CSS dla czcionki Inter
});

const sora = Sora({
    subsets: ["latin"],
    variable: "--font-sora", // definiujemy zmienną CSS dla czcionki Sora
});

export default function RootLayout({children}) {
    return (
        <html lang="pl">
            <body
                className={`${inter.variable} ${sora.variable} relative overflow-x-hidden sora`}
            >
            <Navbar/>
            {children}
            </body>
        </html>
    );
}
