import "./globals.css";
import {Inter, Sora} from "next/font/google";
import Navbar from "@/components/Navbar";
import StateContextProvider from "@/context/StateContext";
import AuthContextProvider from "@/context/AuthContext";
import DisplayContextProvider from "@/context/DisplayContext";
import {Toaster} from "react-hot-toast";
import Debugger from "@/components/Debugger";

export const metadata = {
    title: "Create Next App", description: "Generated by create next app",
};

const inter = Inter({
    subsets: ["latin"], variable: "--font-inter", // definiujemy zmienną CSS dla czcionki Inter
});

const sora = Sora({
    subsets: ["latin"], variable: "--font-sora", // definiujemy zmienną CSS dla czcionki Sora
});

export default function RootLayout({children}) {
    return (<html lang="pl">
        <body className={`${inter.variable} ${sora.variable} relative overflow-x-hidden sora`}>
        <DisplayContextProvider>
            <AuthContextProvider>
                <StateContextProvider>
                    <Toaster/>
                    <Navbar/>
                    {children}
                </StateContextProvider>
            </AuthContextProvider>
        </DisplayContextProvider>
        </body>
        </html>);
}
