import "./globals.css";
import {Inter, Sora} from "next/font/google";
import Navbar from "@/components/Navbar";
import StateContextProvider from "@/context/StateContext";
import AuthContextProvider from "@/context/AuthContext";
import DisplayContextProvider from "@/context/DisplayContext";
import {Toaster} from "react-hot-toast";

export const metadata = {
    title: "Create Next App", description: "Generated by create next app",
};

const inter = Inter({
    subsets: ["latin"], variable: "--font-inter",
});

const sora = Sora({
    subsets: ["latin"], variable: "--font-sora",
});

export default function RootLayout({children}) {
    return (<html lang="pl">
    <body className={`${inter.variable} ${sora.variable} relative overflow-x-hidden sora`}>
    <DisplayContextProvider>
        <AuthContextProvider>
            <StateContextProvider>
                <Toaster/>
                <Navbar/>
                {children}
            </StateContextProvider>
        </AuthContextProvider>
    </DisplayContextProvider>
    </body>
    </html>);
}
